# This is a basic workflow to help you get started with Actions

name: Documentation

on:
  push:
#    paths:
#    - '**.md'
#    - '.github/workflows/doc.yml'

jobs:
  toc:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: TOC Generator
      uses: technote-space/toc-generator@v2.6.1
      with:
        TARGET_PATHS: '.'
        TOC_TITLE: ':link: **Contents**'
        MAX_HEADER_LEVEL: 3

  modules:
    runs-on: ubuntu-latest
    container:
      image: "claranet/terraform-ci:latest"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate modules doc
      run: make doc

    - name: Check for changes
      run: git diff --exit-code

  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run PySpelling
      uses: sbates130272/spellcheck-github-actions@v0.7.0

  dead-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check dead links in Markdown
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        use-verbose-mode: yes
        check-modified-files-only: yes
        config-file: .mlc_config.json

